kaltura/HLS-OSMF

HLSPlugin/src/com/kaltura/hls/m2ts/FLVTranscoder.as
HLSPlugin/src/com/kaltura/hls/manifest/HLSManifestParser.as

Also fixes manifests with / at start of segment paths.

Fix for tricky AAC streams.

---

HLSPlugin/src/com/kaltura/hls/m2ts/FLVTranscoder.as
HLSPlugin/src/com/kaltura/hls/m2ts/NALUProcessor.as
HLSPlugin/src/com/kaltura/hls/m2ts/PESProcessor.as

Went from ~100ms per flush to below 5ms per flush.

Incrementally generate FLV tags.

---

HLSPlugin/src/com/kaltura/hls/HLSDVRTimeTrait.as
HLSPlugin/src/com/kaltura/hls/SubtitleEvent.as
HLSPlugin/src/com/kaltura/hls/SubtitleTrait.as
HLSPlugin/src/com/kaltura/hls/m2ts/FLVTranscoder.as
HLSPlugin/src/com/kaltura/hls/subtitles/TextTrackCue.as
HLSPlugin/src/org/osmf/net/httpstreaming/HLSHTTPNetStream.as
TestPlayer/src/TestPlayer.mxml

Address FEC-2969 and SUP-5002
live WebVTT captions problem

Bjg fix captions

---

HLSPlugin/src/com/kaltura/hls/m2ts/M2TSFileHandler.as

Cap number of bytes converted per frame. FEC-3732

V2.32 FEC 3732

---

HLSPlugin/src/com/kaltura/hls/manifest/HLSManifestEncryptionKey.as

It was missing one byte of padding before.

Rewrote padding logic; now seems to play video with no issues.

---

HLSPlugin/src/com/kaltura/hls/m2ts/M2TSFileHandler.as

Also, improvements to segment begin/end logic.

"Low Water" system to avoid bitrate change artifacts.

---

HLSPlugin/src/org/osmf/net/httpstreaming/HLSHTTPStreamSource.as
KalturaHLSPlugin/src/com/kaltura/kdpfl/plugin/KalturaHLSMediator.as

Hls debug events

---

HLSPlugin/src/com/kaltura/hls/m2ts/M2TSFileHandler.as

Revert "Adjusted low water threshold to more realistic value."

---

HLSPlugin/src/com/kaltura/hls/m2ts/M2TSFileHandler.as

Revert ""Low Water" system to avoid bitrate change artifacts."

---

HLSPlugin/src/com/kaltura/hls/HLSIndexHandler.as

revert merge (debugVisualization->2.34) mistake

---

Makefile
README.md
TestPlayer/html-template/index.html
TestPlayer/src/TestPlayer.mxml

DP stuff ware removed during big merge to the v2.34 branch

DP add-ons ware removed during merge from 2.34 branch

---

HLSPlugin/src/com/kaltura/hls/m2ts/PESProcessor.as

Further fix to large PTS/DTS wraparound cases.

---

HLSPlugin/src/com/kaltura/hls/HLSIndexHandler.as
HLSPlugin/src/com/kaltura/hls/m2ts/FLVTranscoder.as
HLSPlugin/src/com/kaltura/hls/m2ts/M2TSFileHandler.as
HLSPlugin/src/com/kaltura/hls/m2ts/PESProcessor.as
HLSPlugin/src/com/kaltura/hls/m2ts/TSPacketParser.as
HLSPlugin/src/org/osmf/net/httpstreaming/HLSHTTPNetStream.as
HLSPlugin/src/org/osmf/net/httpstreaming/HLSHTTPStreamDownloader.as

retargeting seek fix to the v2.36

Bjg better wrap fix

---

HLSPlugin/src/com/kaltura/hls/HLSIndexHandler.as
HLSPlugin/src/com/kaltura/hls/m2ts/FLVTranscoder.as
HLSPlugin/src/com/kaltura/hls/m2ts/M2TSFileHandler.as
HLSPlugin/src/com/kaltura/hls/m2ts/PESProcessor.as
HLSPlugin/src/com/kaltura/hls/m2ts/TSPacketParser.as
HLSPlugin/src/org/osmf/net/httpstreaming/HLSHTTPNetStream.as
HLSPlugin/src/org/osmf/net/httpstreaming/HLSHTTPStreamDownloader.as

Revert "Bjg better wrap fix"

---

tools/FLVTemplate.bt
tools/MpegTS.bt
tools/TamarinParser/M2TSTest.as
tools/TamarinParser/Makefile
tools/TamarinParser/README.md
tools/TamarinParser/build.as3

010 Templates and Standalone Tamarin Parser

---

HLSPlugin/src/com/kaltura/hls/HLSLoader.as

I realized that I forgot the abs here so it would only work in certain cases, not generally.

Fix bitrate distance calculation.

---

HLSPlugin/src/com/kaltura/hls/HLSIndexHandler.as
HLSPlugin/src/org/osmf/net/httpstreaming/HLSHTTPNetStream.as

retargeted from v2.37 to v2.37-Massive-Buffers-Refactor

Fix some crashes related to index handler initialization.

---

HLSPlugin/src/com/kaltura/hls/HLSIndexHandler.as
HLSPlugin/src/com/kaltura/hls/m2ts/M2TSFileHandler.as
HLSPlugin/src/com/kaltura/hls/m2ts/PESProcessor.as
HLSPlugin/src/org/osmf/net/httpstreaming/HLSHTTPNetStream.as

VOD streams now always start playback at zero.

---

HLSPlugin/src/com/kaltura/hls/HLSIndexHandler.as
HLSPlugin/src/org/osmf/net/httpstreaming/HLSHTTPNetStream.as

This behaves properly for me when seeking on DVR.
It is in QA, should have results by tomorrow 9AM my time.

Assorted small time logic cleanups.

---

HLSPlugin/src/com/kaltura/hls/HLSIndexHandler.as
HLSPlugin/src/com/kaltura/hls/HLSLoader.as
HLSPlugin/src/com/kaltura/hls/manifest/HLSManifestParser.as
HLSPlugin/src/org/osmf/net/httpstreaming/HLSHTTPNetStream.as

Add support for min/max/preferred bitrates.	
Fix for bad duration reporting.
Simplified and improved liveEdgeMinueWindowDuration calculation logic.

Bjg fec 4704

---

HLSPlugin/src/com/kaltura/hls/DebugSwitchManager.as
HLSPlugin/src/com/kaltura/hls/HLSIndexHandler.as
HLSPlugin/src/com/kaltura/hls/m2ts/FLVTranscoder.as
HLSPlugin/src/com/kaltura/hls/m2ts/M2TSNetLoader.as
HLSPlugin/src/com/kaltura/hls/m2ts/NALUProcessor.as

Bitrate switch debugging and better BEF guesses.
